ConnectionError(MaxRetryError("HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //www.petsathome.com/robots.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4e5dc814e0>: Failed to establish a new connection: [Errno -2] Name or service not known',))",),)
ConnectionError(MaxRetryError("HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //www.petsathome.com/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f831c6f2f60>: Failed to establish a new connection: [Errno -2] Name or service not known',))",),)
